version: '3.1'

services:
  db: 
    image: mysql:latest
    ports:
     - 8080:3306
    environment: 
      MYSQL_ROOT_PASSWORD: secret-pw
      MYSQL_DATABASE: images
    volumes:
      - my-db:/var/lib/mysql
      - ./init-script.sql:/docker-entrypoint/init.sql
volumes:
  my-db:


