version: '3.1'

services:
  db: 
    image: mysql
    ports:
     - "8081:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: secret-pw
      MYSQL_DATABASE: images
    volumes:
      - "justtest-db:/var/lib/mysql"
      - "./init-script.sql:/docker-entrypoint-initdb.d/init.sql"
volumes:
  justtest-db:


