name: Test, Build, and Push

on: [push]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'  

      - name: Run tests
        run: | 
          cd webapp
          go test ./...
  building-executable:
    runs-on: ubuntu-latest
    needs: unit-testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Build the Go application
        run: | 
          cd webapp
          go build -o detection_program

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: my-go-executable
          path: detection_program

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: building-executable
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download built binary
        uses: actions/download-artifact@v4
        with:
          name: my-go-executable
          path: myapp
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: | 
          cd webapp
          docker build --build-arg MYSQL_PASSW=${{ secrets.MYSQL_PASSW }} -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
