name: Test, Build, and Push

on: [push]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'  

      - name: Run tests
        run: go test ./...
  building-executable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Build the Go application
        run: go build -o myapp

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: my-go-executable
          path: myapp